
export const CARD_TITLES: string[] = [
  "Flame Serpent",
  "Iron Golem",
  "Shadow Stalker",
  "Celestial Guardian",
  "Mystic Owl",
  "Stone Titan",
  "Storm Drake",
  "Forest Sprite",
  "Abyssal Fiend",
  "Sunstone Paladin",
  "Glacier Elemental",
  "Volcanic Imp",
  "Ancient Treant",
  "Whispering Banshee",
  "Knight of the Rose",
  "Desert Djinn",
  "Swamp Hydra",
  "Sky Griffin",
  "Underworld Lich",
  "Psionic Master",
  // Add more unique titles or variations to reach 40 for two 20-card decks
  "Flame Serpent II",
  "Iron Golem II",
  "Shadow Stalker II",
  "Celestial Guardian II",
  "Mystic Owl II",
  "Stone Titan II",
  "Storm Drake II",
  "Forest Sprite II",
  "Abyssal Fiend II",
  "Sunstone Paladin II",
  "Glacier Elemental II",
  "Volcanic Imp II",
  "Ancient Treant II",
  "Whispering Banshee II",
  "Knight of the Rose II",
  "Desert Djinn II",
  "Swamp Hydra II",
  "Sky Griffin II",
  "Underworld Lich II",
  "Psionic Master II",
];

